services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        networks:
            - symfony
        depends_on:
            - database

  ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: app
            # You should definitely change the password in production
            POSTGRES_PASSWORD: myverysecretpassword
            POSTGRES_USER: app
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - symfony
###< doctrine/doctrine-bundle ###

networks:
    symfony:
        driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
