### Calculate Price
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### Execute Purchase
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}

### Create Discount Coupon (Coupon types, for example, can be 'fix' and 'percent')
POST http://127.0.0.1:8337/discounts
Accept: application/json
Content-Type: application/json

{
  "couponCode": "D150",
  "discount": 150,
  "couponType": "percent"
}

### Create Product
POST http://127.0.0.1:8337/products
Accept: application/json
Content-Type: application/json

{
  "name": "Huawei Phone",
  "price": "zxczx"
}

### Create Tax
POST http://127.0.0.1:8337/taxes
Accept: application/json
Content-Type: application/json

{
  "countryName": "Греция",
  "countryCode": "GR",
  "taxRate": 24.0
}
